name: music320finalproject
channels:
  - defaults
dependencies:
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libcxx=20.1.8
  - libffi=3.4.4
  - libiconv=1.16
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=25.2
  - python=3.9.6
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - attrs==25.4.0
      - cffi==2.0.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jax==0.4.30
      - jaxlib==0.4.30
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - mediapipe==0.10.21
      - ml-dtypes==0.5.3
      - numpy==1.26.4
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - packaging==25.0
      - pillow==11.3.0
      - protobuf==4.25.8
      - pycparser==2.23
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - scipy==1.13.1
      - sentencepiece==0.2.1
      - six==1.17.0
      - sounddevice==0.5.3
      - zipp==3.23.0
prefix: /opt/miniconda3/envs/music320finalproject
